export default {
  accessToken: (state) => state.user.accessToken,
  collapse: (state) => state.settings.collapse,
  cachedViews: (state) => state.tagsView.cachedViews,
  device: (state) => state.settings.device,
  errorLogs: (state) => state.errorLog.logs,
  header: (state) => state.settings.header,
  layout: (state) => state.settings.layout,
  logo: (state) => state.settings.logo,
  userName: (state) => state.user.userName,
  roles: (state) => state.user.roles,
  routes: (state) => state.permission.routes,
  selectedTag: (state) => state.tagsView.selectedTag,
  srcTableCode: (state) => state.table.srcCode,
  tagsView: (state) => state.settings.tagsView,
  visitedViews: (state) => state.tagsView.visitedViews,
};
